In [16]:
import pandas as pd
df_games = pd.read_csv('./gamesNoGS.csv', parse_dates=['release_date'])
df_genres = pd.read_csv('./games_genres.csv')
# Combinar los DataFrames
df = pd.merge(df_games, df_genres, on='id')

# Eliminar columnas innecesarias
# df.drop(['release_date'], axis=1, inplace=True)

# Rellenar valores faltantes con ceros
df.fillna(0, inplace=True)

In [17]:
df_games.head()

                  app_name release_date      id  precios
0      Lost Summoner Kitty   2018-01-04  761140        1
1                Ironbound   2018-01-04  643980        0
2  Real Pool 3D - Poolians   2017-07-24  670290        0
3                  弹炸人2222   2017-12-07  767400        1
4    Battle Royale Trainer   2018-01-04  772540        1

In [18]:
df.head()

,app_name,release_date,id,precios,Indie,Action,Casual,Adventure,Strategy,Simulation,RPG,Free to Play,Early Access,Sports,Massively Multiplayer,Racing
0,Lost Summoner Kitty,2018-01-04,761140,1,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ironbound,2018-01-04,643980,0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,Real Pool 3D - Poolians,2017-07-24,670290,0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,弹炸人2222,2017-12-07,767400,1,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Battle Royale Trainer,2018-01-04,772540,1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

def recomendacion_juego(id_producto, df, num_recomendaciones=5):
    # Obtener el vector de géneros del juego de entrada
    juego_vector = df[df['id'] == id_producto].iloc[:, 3:].values.reshape(1, -1)
    # Calcular la similitud del coseno entre el juego de entrada y todos los demás juegos
    similarity_scores = cosine_similarity(df.iloc[:, 3:], juego_vector)
    # Obtener los índices de los juegos más similares
    similar_indices = similarity_scores.argsort(axis=0)[::-1][:num_recomendaciones]

    # Obtener los nombres de los juegos recomendados
    recomendaciones = df.iloc[similar_indices.ravel(), :]['app_name'].values.tolist()

    return recomendaciones

# Ejemplo de uso
id_producto = 10  # ID de un juego de entrada
recomendaciones = recomendacion_juego(id_producto, df)
print(recomendaciones)

['TRIZEAL Remix', 'Killing Floor - Community Weapon Pack 2', 'Tron 2.0', 'Aliens vs Predator™ Bughunt Map Pack', 'Escape From Paradise 2']